from datetime import timedelta
from typing import Union, overload


class Watt:
    value: float
    def __init__(self, value: float) -> None: ...

    # Overloads handle different multiplication directions
    def __mul__(self, other: timedelta) -> WattHour: ...
    def __rmul__(self, other: timedelta) -> WattHour: ...

    def __add__(self, other: Watt) -> Watt: ...
    def __sub__(self, other: Watt) -> Watt: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...


class WattHour:
    value: float
    def __init__(self, value: float) -> None: ...

    def __truediv__(self, other: timedelta) -> Watt: ...
    def __mul__(self, other: EuroPerWh) -> Euro: ...

    def __add__(self, other: WattHour) -> WattHour: ...
    def __sub__(self, other: WattHour) -> WattHour: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...


class Euro:
    value: float
    def __init__(self, value: float) -> None: ...

    def __truediv__(self, other: WattHour) -> EuroPerWh: ...

    def __add__(self, other: Euro) -> Euro: ...
    def __sub__(self, other: Euro) -> Euro: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...


class EuroPerWh:
    value: float
    def __init__(self, value: float) -> None: ...

    def __mul__(self, other: WattHour) -> Euro: ...

    def __add__(self, other: EuroPerWh) -> EuroPerWh: ...
    def __sub__(self, other: EuroPerWh) -> EuroPerWh: ...
    def __repr__(self) -> str: ...
    def __float__(self) -> float: ...
